#!/bin/bash -eu

# where the log file is saved
LOG_FILE="./logfile"

# get date formated
date_and_time=$(date +"%T %d/%m/%y")

# get uniq logged in user, as array
user_logedin=($(who -u | perl -pnE "s|(^.*?) .*|\1|g" | uniq))

# pretty format uptime
uptime=$(uptime -p)

# format USER_LOGEDIN, if
for i in $(seq 1 ${#user_logedin[@]}); do
	((i--))
	if [ "${user_logedin[${i}]}" == "$(whoami)" ]; then
		user_logedin[${i}]="${user_logedin[${i}]} (you)"
	fi
done

# save to a log file, thank to code the block
{
	printf "[DATE AND TIME] : %s\n" "${date_and_time}"
	printf "[USER LOGED IN]\n"
	for i in $(seq 1 ${#user_logedin[@]}); do
		((i--))
		printf -- "                - %s\n" "${user_logedin[${i}]}"
	done
	printf "[UPTIME       ] : ${uptime}\n"
} > "${LOG_FILE}"
